import "@/styles/global.css";

export const metadata = {
  title: "Quiz Eat",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="" style={{ backgroundColor: "#353D62" }}>
        {children}
      </body>
    </html>
  );
}
