import "@/styles/global.css";
import { AuthProvider } from "./Providers";
// import StoreProvider from "./StoreProvider";
import StoreProvider from "./StoreProvider";

export const metadata = {
  title: "Quiz Eat",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="" style={{ backgroundColor: "#353D62" }}>
        <AuthProvider>
          <StoreProvider>{children}</StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
